version: '3.8'

x-build: &build
  context: .
  dockerfile: ./Dockerfile
  args:
    VERSION: '20.04'
    APT_PROXY: "${APT_PROXY}"
    USER: "${DOCKER_USER}"
    WORKDIR: "${DOCKER_WORKDIR}"
  target: dev

x-base: &base
  env_file: .env
  container_name: "${PRODUCT_NAME}"
  working_dir: "${DOCKER_WORKDIR}"
  user: "${DOCKER_USER}"
  volumes:
    - "./:${DOCKER_MOUNT}:ro"
  environment:
    - RUN_ON_DOCKER=true
    - USER=${DOCKER_USER}
  cap_add:
    - SYS_ADMIN
  devices:
    - "/dev/fuse"
  security_opt:
    - "apparmor:unconfined"
  stdin_open: true # docker run -i
  tty: true        # docker run -t

services:
  test:
    <<: *base
    build:
      <<: *build
      target: dev
    entrypoint: "./scripts/test"

  play:
    <<: *base
    build:
      <<: *build
      target: dev
    entrypoint: "/bin/bash"

  gui:
    image: dorowu/ubuntu-desktop-lxde-vnc
    <<: *base
    user: root
    ports:
      - '5900:5900'
    environment:
      - VNC_PASSWORD=${VNC_PASSWORD}
      - USER=${DOCKER_USER}
    volumes:
      - '/dev/shm:/dev/shm'
      - "./:${DOCKER_MOUNT}:ro"
