#!/usr/bin/env bash

set -euEo pipefail

set -o allexport
. ./.env
set +o allexport

readonly tmp_dir="$(mktemp -d)"
cd "$tmp_dir"

on_exit() {
  rm -rf "$tmp_dir"
}
trap on_exit INT TERM EXIT

sudo apt update -y
sudo apt install -y curl

# Vagrant

vagrant plugin install vagrant-aws
vagrant plugin install vagrant-readenv

# install docker
