#!/usr/bin/env bash

set -euEo pipefail

set -o allexport
. ./.env
set +o allexport

readonly tmp_dir="$(mktemp -d)"
cd "$tmp_dir"

on_exit() {
  rm -rf "$tmp_dir"
}
trap on_exit INT TERM EXIT

sudo apt update -y
sudo apt install -y curl

# Vagrant
if ! type -P vagrant &> /dev/null; then
  readonly latest="$(curl --silent "https://api.github.com/repos/hashicorp/vagrant/tags" | sed 's/\"//g' | grep -P 'name\:\s+v\d+\.\d+\.\d+,' | grep -Po '\d+\.\d+\.\d+' | head -n 1)"
  wget "https://releases.hashicorp.com/vagrant/${latest}/vagrant_${latest}_x86_64.deb" -O vagrant_x86_64.deb

  sudo apt install -y ./vagrant_x86_64.deb

  vagrant plugin install vagrant-aws
  vagrant plugin install vagrant-readenv
fi

# install docker
