#!/usr/bin/env bash
# shellcheck disable=SC2154
set -euEo pipefail

set -o allexport
. ./.env
set +o allexport

readonly tmp_dir="$(mktemp -d)"
cd "$tmp_dir"

on_exit() {
  rm -rf "$tmp_dir"
}
trap on_exit INT TERM EXIT


# Install docker
wget -qO - "${iscript}/docker/docker-ubuntu" | bash
# Install Vagrant
wget -qO - "${iscript}/vagrant/vagrant-ubuntu" | bash
vagrant plugin install vagrant-aws
vagrant plugin install vagrant-readenv
